/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=GitHubWebhookProcessorEnv src/env.generated.d.ts` (hash: cab69793c7039cbee49133656e1125de)
interface __BaseEnv_GitHubWebhookProcessorEnv {
	WORKLOAD_IDENTITY_TOKEN_AUDIENCE: "https://cyspbot.local";
	GITHUB_APP_TOKEN_BROKER_TOKEN_ENDPOINT: "https://github-app-token-broker-local/token";
	GITHUB_APP_TOKEN_BROKER: Fetcher /* github-app-token-broker-local */;
	WORKLOAD_IDENTITY_ISSUER: Service /* entrypoint WorkloadIdentityIssuer from workload-identity-issuer-local */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GitHubWebhookProcessorEnv {}
}
interface GitHubWebhookProcessorEnv extends __BaseEnv_GitHubWebhookProcessorEnv {}
