/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=CyspbotTokenProxyEnv src/env.generated.d.ts` (hash: 1c5b8e9e3f7bea146b96f66ca338534a)
interface __BaseEnv_CyspbotTokenProxyEnv {
	TOKEN_PROXY_ENDPOINT: "https://broker.example/github/apps/example-app/token";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CyspbotTokenProxyEnv {}
}
interface CyspbotTokenProxyEnv extends __BaseEnv_CyspbotTokenProxyEnv {}
