/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=CyspbotEnv src/env.generated.d.ts` (hash: 65616e593d9284c4f34cab871d60c145)
interface __BaseEnv_CyspbotEnv {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CyspbotEnv {}
}
interface CyspbotEnv extends __BaseEnv_CyspbotEnv {}
