/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=CyspbotEnv src/env.generated.d.ts` (hash: 04eb5a15a19a875dc20ac982a620222b)
interface __BaseEnv_CyspbotEnv {
	WORKLOAD_IDENTITY_TOKEN_AUDIENCE: "https://cyspbot.local";
	GITHUB_APP_TOKEN_BROKER_TOKEN_ENDPOINT: "https://github-app-token-broker-local/token";
	GITHUB_APP_TOKEN_BROKER: Fetcher /* github-app-token-broker-local */;
	WORKLOAD_IDENTITY_ISSUER: Service /* entrypoint WorkloadIdentityIssuer from workload-identity-issuer-local */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CyspbotEnv {}
}
interface CyspbotEnv extends __BaseEnv_CyspbotEnv {}
