/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=CyspbotEnv src/env.generated.d.ts` (hash: 07b541e6b965421b25b8861d3ff56468)
interface __BaseEnv_CyspbotEnv {
	TOKEN_PROXY_ENDPOINT: "https://broker.example/github/apps/example-app/token";
	GITHUB_APP_TOKEN_BROKER: Fetcher /* github-app-token-broker-local */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_CyspbotEnv {}
}
interface CyspbotEnv extends __BaseEnv_CyspbotEnv {}
