/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/cyspbot-github-webhook-receiver/wrangler.jsonc --include-runtime=false --env-interface=GitHubWebhookReceiverBindings workers/cyspbot-github-webhook-receiver/src/bindings.generated.d.ts` (hash: 8b28f1f8eb70a0f6037a5ccc80821947)
interface __BaseEnv_GitHubWebhookReceiverBindings {
	GITHUB_APP_ID: "000000";
	GITHUB_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GitHubWebhookReceiverBindings {}
}
interface GitHubWebhookReceiverBindings extends __BaseEnv_GitHubWebhookReceiverBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_APP_ID" | "GITHUB_WEBHOOK_SECRET">> {}
}
