/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=GitHubWebhookReceiverEnv src/env.generated.d.ts` (hash: e576f60a86723aa60f19cabaa69eef66)
interface __BaseEnv_GitHubWebhookReceiverEnv {
	GITHUB_APP_ID: "000000";
	GITHUB_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GitHubWebhookReceiverEnv {}
}
interface GitHubWebhookReceiverEnv extends __BaseEnv_GitHubWebhookReceiverEnv {}
