/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=GitHubWebhookReceiverEnv src/env.generated.d.ts` (hash: 10fb3bf8e4bf5a5623b991a3738c9bb2)
interface __BaseEnv_GitHubWebhookReceiverEnv {
	GITHUB_APP_ID: "000000";
	GITHUB_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GitHubWebhookReceiverEnv {}
}
interface GitHubWebhookReceiverEnv extends __BaseEnv_GitHubWebhookReceiverEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_APP_ID" | "GITHUB_WEBHOOK_SECRET">> {}
}
