/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=GitHubWebhookReceiverEnv src/env.generated.d.ts` (hash: 120a4df8d8249fec673785b851b0443a)
interface __BaseEnv_GitHubWebhookReceiverEnv {
	GITHUB_WEBHOOK_JOBS: Queue;
	GITHUB_APP_ID: "000000";
	GITHUB_WEBHOOK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_GitHubWebhookReceiverEnv {}
}
interface GitHubWebhookReceiverEnv extends __BaseEnv_GitHubWebhookReceiverEnv {}
