/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/cyspbot-token-exchange/wrangler.jsonc --include-runtime=false --env-interface=TokenExchangeBindings workers/cyspbot-token-exchange/src/bindings.generated.d.ts` (hash: 6fbd4b73eaafe8e06325d97b37a11f50)
interface __BaseEnv_TokenExchangeBindings {
	TOKEN_EXCHANGE_RATE_LIMIT: RateLimit;
	GITHUB_API_BASE_URL: "https://api.github.com";
	GITHUB_APP_ID: "000000";
	GITHUB_APP_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_TokenExchangeBindings {}
}
interface TokenExchangeBindings extends __BaseEnv_TokenExchangeBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_API_BASE_URL" | "GITHUB_APP_ID" | "GITHUB_APP_PRIVATE_KEY">> {}
}
