/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=TokenExchangeEnv src/env.generated.d.ts` (hash: 90f45f28b7f4ff038b0e3b672c1621fb)
interface __BaseEnv_TokenExchangeEnv {
	TOKEN_EXCHANGE_RATE_LIMIT: RateLimit;
	GITHUB_API_BASE_URL: "https://api.github.com";
	GITHUB_APP_ID: "000000";
	GITHUB_APP_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_TokenExchangeEnv {}
}
interface TokenExchangeEnv extends __BaseEnv_TokenExchangeEnv {}
