name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  validation:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          run_install: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: node --run format:check

      - name: Check generated environment types
        run: node --run env-types:check

      - name: Lint
        run: node --run lint

      - name: Type check
        run: node --run typecheck

      - name: Check unused code
        run: node --run knip

      - name: Dry run all Workers
        run: node --run deploy:dry-run

  test:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/ci-test.yml

  ci:
    name: ci
    runs-on: ubuntu-latest
    needs:
      - validation
      - test
    if: ${{ always() }}
    steps:
      - name: Require all CI jobs to pass
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            exit 1
          fi

          if [[ "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi

          if [[ "${{ contains(needs.*.result, 'skipped') }}" == "true" ]]; then
            exit 1
          fi
