name: run-cyspbot-deploy-update

on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  run:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: chikachow/cyspbot-app-token-action@3ea722e716c165db3ed77ade9a0a0ca49ec2f8a0 # v0.0.9
        id: cyspbot
        with:
          resource: https://api.github.com/repos/chikachow/cyspbot-deploy
          scope: actions:write

      - name: Run cyspbot-deploy update workflow
        run: gh workflow run update-cyspbot.yml --repo chikachow/cyspbot-deploy --ref main
        env:
          GH_TOKEN: ${{ steps.cyspbot.outputs.token }}
